### ISSUE TITLE
Add DMRG unit test

### ISSUE THREAD

**Issue by mscho527** [oimeitei/quemb#42]
> @ShaunWeatherly Would it make more sense to leave the `pytest` items for the DMRG as is, but add a decorator? i.e.
> 
> https://github.com/oimeitei/quemb/blob/0f3c6c2d7eea70d4a6fb2bdb4c292b8d7bfe8068/tests/eri_onthefly_test.py#L12

@mscho527 Unfortunately these tests wouldn't work regardless unless we make the `pyscf.dmrgscf` module required. Without that, they just would redundantly test other parts of QuEmb. 

*EDIT: actually I see what you're saying, I'll fix up the unit tests and add them in a new PR.

_Originally posted by @ShaunWeatherly in https://github.com/oimeitei/quemb/issues/41#issuecomment-2417592653_

**Comment by ShaunWeatherly** [comment]
#44
